\begin{question}
Eseguiamo un test t di Student per due campioni indipendenti. Sia alpha = 0.01. Si interpreti l'output fornito da R.

\begin{verbatim}
	Two Sample t-test

data:  x1 and x2
t = 3.5466, df = 30, p-value = 0.001305
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  6.736379 25.026642
sample estimates:
mean of x mean of y
 82.39235  66.51084
\end{verbatim}

\begin{answerlist}
   \item Possiamo rigettare H0 perché il valore-p è minore di alpha = 0.01.
   \item Non possiamo rigettare H0 perché il valore-p è maggiore di alpha = 0.01.
   \item Possiamo rigettare H0 perché il valore-p è maggiore di alpha = 0.01.
   \item Non possiamo rigettare H0 perché il valore-p è minore di alpha = 0.01.
   \item Non possiamo giungere ad una conclusione su H0 perché l'output di R non ci fornire il valore critico della regione di rifiuto.
\end{answerlist}

 \end{question}

\begin{solution}
x
\end{solution}

\exname{test_ipotesi_14}
\extype{mchoice}
\exsolution{10000}
\exshuffle{TRUE}
