\begin{question}
Si considerino i seguenti valori della variabile dipendente in due gruppi indipendenti. 
Gruppo 1: 4, 1, 3; gruppo 2: 7, 6, 7, 12.
Assumendo l'equaglianza delle varianze nella popolazione, si calcoli il test $t$ di Student per la differenza tra le medie di due gruppi indipendenti.
Si scelga l'affermazione corretta.

\begin{answerlist}
   \item Il test $t$ di Student suggerisce l'esistenza di una differenza statisticamente significativa tra le medie dei due gruppi, $t_{5}$ = -3.02, $p$ = 0.0293.
    \item Il test $t$ di Student suggerisce l'esistenza di una differenza statisticamente significativa tra le medie dei due gruppi, $t_{5}$ = -3.52, $p$ = 0.0169.
   \item Il test $t$ di Student non offre evidenze di una differenza statisticamente significativa tra le medie dei due gruppi, $t_{5}$ = -1.15, $p$ = 0.3021.
   \item Il test $t$ di Student non offre evidenze di una differenza statisticamente significativa tra le medie dei due gruppi, $t_{5}$ = -0.91, $p$ = 0.4045.
	 \item Il test $t$ di Student suggerisce l'esistenza di una differenza statisticamente significativa tra le medie dei due gruppi, $t_{5}$ = 2.81, $p$ = 0.0375.
\end{answerlist}

 \end{question}

\begin{solution}
y1 <- c(4, 1, 3)

y2 <- c(7, 6, 7, 12)

t.test(y1, y2, var.equal = TRUE)
\end{solution}

\exname{ttest_2}
\extype{mchoice}
\exsolution{10000}
\exshuffle{TRUE}
